player:
	javac Main.java
	clear
	java Main 1
board :
	javac Main.java
	clear
	java Main 2
game :
	javac Main.java
	clear
	java Main 3
process :
	javac Main.java
	clear
	java Main 4
clean:
	rm *.class

