player:
	javac Main.java
	clear
	java Main 1
board :
	javac Main.java
	clear
	java Main 2
game :
	javac Main.java
	clear
	java Main 3
process :
	javac Main.java
	clear
	java Main 4
grid:
	javac GridOfButtons.java
	clear
	java GridOfButtons
flow:
	javac FlowLayoutDemo.java
	clear
	java FlowLayoutDemo
ui :
	javac Connect4GUI.java
	clear
	java Connect4GUI
clean:
	rm *.class

